### ISSUE TITLE
Can not add existing secret to homeassistant-chart Postgres

### ISSUE THREAD

**Issue by Brice187** [pree/helm-charts#436]
values.yaml
```yaml
# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  # TODO: FixMe!
  enabled: true
  username: homeassistant
  database: homeassistant
  existingSecret: postgres-secret
  secretKeys:
    userPasswordKey: password
```
secret.yaml
```
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: homeassistant
type: Opaque
data:
  database: redacted
  password: redacted
  username: redacted
```

When I start a fresh instance, I get following logout:

```
$ kubectl -n homeassistant logs homeassistant-postgresql-0 -f
postgresql 09:04:53.81 INFO  ==> 
postgresql 09:04:53.81 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 09:04:53.81 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 09:04:53.81 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 09:04:53.81 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
postgresql 09:04:53.82 INFO  ==> 
postgresql 09:04:53.91 INFO  ==> ** Starting PostgreSQL setup **
postgresql 09:04:54.10 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 09:04:54.11 INFO  ==> Loading custom pre-init scripts...
postgresql 09:04:54.11 INFO  ==> Initializing PostgreSQL database...
postgresql 09:04:54.21 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 09:04:54.21 INFO  ==> Generating local authentication configuration
postgresql 09:05:01.89 INFO  ==> Starting PostgreSQL in background...
postgresql 09:05:03.81 INFO  ==> Changing password of postgres
postgresql 09:05:04.01 INFO  ==> Creating user home-assistant
postgresql 09:05:04.20 INFO  ==> Granting access to "home-assistant" to the database "home-assistant"
postgresql 09:05:04.60 INFO  ==> Setting ownership for the 'public' schema database "home-assistant" to "home-assistant"
postgresql 09:05:04.91 INFO  ==> Configuring replication parameters
postgresql 09:05:05.31 INFO  ==> Configuring synchronous_replication
postgresql 09:05:05.31 INFO  ==> Configuring fsync
postgresql 09:05:05.83 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 09:05:06.41 INFO  ==> Loading custom scripts...
postgresql 09:05:06.42 INFO  ==> Enabling remote connections

postgresql 09:05:06.51 INFO  ==> ** PostgreSQL setup finished! **
postgresql 09:05:06.80 INFO  ==> ** Starting PostgreSQL **
2024-10-17 09:05:06.918 GMT [1] LOG:  pgaudit extension initialized
2024-10-17 09:05:07.009 GMT [1] LOG:  starting PostgreSQL 17.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
...
```
As you can see, the given values are ignored (`Granting access to "home-assistant" to the database "home-assistant"`)

There are too many layers of abstraction, do you have any hints or a working example?

**Comment by Brice187** [comment]
nevermind, values.yaml should be:

```
postgresql:
  enabled: true
  auth:
    existingSecret: postgres-secret
```
